controller_names:
  - locobot/arm_controller
  - locobot/gripper_controller

locobot/arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - waist
    - shoulder
    - elbow
    - wrist_angle

locobot/gripper_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - left_finger
