robot_radius: 0.2

laser_layer:
  obstacle_range: 2.5
  raytrace_range: 13.0
  max_obstacle_height: 0.7
  track_unknown_space: true
  observation_sources: rplidar
  rplidar:
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true
    inf_is_valid: true

depth_layer:
  obstacle_range: 2.5
  raytrace_range: 9.0
  max_obstacle_height: 0.7
  track_unknown_space: true
  observation_sources: depth
  depth:
    data_type: PointCloud2
    topic: rtabmap/depth/color/obstacles
    marking: true
    clearing: true

inflation_layer:
  cost_scaling_factor: 2.5
  inflation_radius: 0.3
