cluster_max_size: 1000
cluster_min_size: 100
cluster_tol: 0.02
plane_dist_thresh: 0.010000000000000002
plane_max_iter: 50
ror_min_neighbors: 5.0
ror_radius_search: 0.01
voxel_leaf_size: 0.005
x_filter_max: 0.25
x_filter_min: -0.25
y_filter_max: 0.25
y_filter_min: -0.15000000000000002
z_filter_max: 0.66
z_filter_min: 0.31000000000000005
